version: '3'

networks:
  october_web_net:
    driver: bridge

services:
  reverse-proxy:
    container_name: web_proxy
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./.docker/dev/nginx/conf.d/certificates:/etc/nginx/certs
      - ./.docker/dev/nginx/conf.d/app.conf:/etc/nginx/conf.d/app.conf
    networks:
      - october_web_net

  web_webserver:
    container_name: web_webserver
    build:
      context: .
      dockerfile: ./.docker/dev/Dockerfile
    volumes:
      - ./:/var/www/html
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal
      APACHE_DOCUMENT_ROOT: /var/www/html/public
      CERT_NAME: dockeroctober.test
      CMS_LINK_POLICY: secure
      VIRTUAL_HOST: dockeroctober.test
      VIRTUAL_PROTO: http
      VIRTUAL_PORT: 80
    networks:
      - october_web_net

  web_mysql:
    image: mysql:5.7
    container_name: web_mysql
    ports:
      - "3406:3306"
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    command: [--max-allowed-packet=67108864]
    networks:
      - october_web_net

  web_redis:
    image: redis
    container_name: web_redis
    ports:
      - "6379:6379"
    networks:
      - october_web_net

  web_mailhog:
    image: mailhog/mailhog
    container_name: web_mailhog
    ports:
      - "1022:1025"
      - "8025:8025"
    networks:
      - october_web_net
